#3
urfu-2020/team-8 pull request #5
Opened 2021-04-09 16:47 UTC by Svetlana1200

2021-04-10 21:03 UTC, toplenboren commented
Круто!

Мне особенно нравится то, что ты сразу же закинула сюда историю с отправкой сообщений

Оставил фидбек по дизайну и внешнему виду [в фигме](https://www.figma.com/file/ogaMcEup2pUi1Ct22rEeyX/Feedback?node-id=0%3A1)

Оставил фидбек по коду в ревью :)

2021-04-10 21:43 UTC, toplenboren requested changes

2021-04-10 21:43 UTC, toplenboren commented on src/Components/App/App.css
> +.chats {
Обычно, если используется UI-kit к стилям для позиционирования стараются не прибегать. Скорее всего в ките уже все определено.

Например, в Material, который мы используем есть [Grid](https://material-ui.com/components/grid/)

Кажется, лучше использовать его. Что думаешь?

2021-04-10 21:43 UTC, toplenboren commented on src/Components/App/App.js
> +          <Box className="chats" height={window.innerHeight * 65 / 100}>
Если мы указываем height так, то при `resize` окна у нас не будет меняться высота. 

Давай лучше придумаем как это сделать через стили? Мне кажется, если мы будем использовать компоненты для позиционирования из материала, то мы даже не столкнемся с этой проблемой

2021-04-10 21:43 UTC, toplenboren commented on src/Components/Chat/Chat.js
> +class Chat extends React.Component {
В `react` есть два способа создания компонентов - функциональные и классовые.

У классовых более богатый API, но функциональные проще и более лаконично написаны. 
Сейчас обычно пишут сразу на функциональных

Здесь, кажется, лучше использовать именно функциональный, что думаешь?

https://ru.reactjs.org/docs/components-and-props.html

2021-04-10 21:43 UTC, toplenboren commented on src/Components/Chat/Chat.js
> +class Chat extends React.Component {
Дополнительно, давай сразу же раскрывать какие props принимает компонент? 

 Я бы сделал такую сигнатуру у функции:
 
 ```(jsx)
 function Contact({name, lastText, time, onClick}) {
   return (
     <Button variant="outlined" className="chat" onClick={() => onClick(name)}>
          <Avatar alt="{name}" src={avatar}/>
          <Box className="infoChat">
            <Typography>
              {name}
            </Typography>
            <Typography>
              {lastText}
            </Typography>
          </Box>
          <Typography className="timeLastMessage">
            {time}
          </Typography>
        </Button>
   )
 }
 
 
 ```

2021-04-10 21:43 UTC, toplenboren commented on src/Components/Chat/Chat.js
> +class Chat extends React.Component {
Ну и каж-ся это не `Chat` а `Contact`

2021-04-10 21:43 UTC, toplenboren commented on src/Components/CurrentChat/CurrentChat.js
> +              {this.renderMessage(9)}
Коллекции в React обычно рендерят так:

```
data = [{name, surname}, {name, surname}, {name, surname}]

return (
  <div>
    {data.map(element => <Message name=element.name surname=element.surname/>)
  </div>
)
```

2021-04-10 21:43 UTC, toplenboren commented on src/Components/Header/Header.js
> +        <Box className="header" height={window.innerHeight * 8 / 100}>
^^

2021-04-10 21:43 UTC, toplenboren commented on src/Components/Header/Header.js
> +        <Box className="header" height={window.innerHeight * 8 / 100}>
Кстати, в Material уже есть компонент, который называется Nav, это как раз шапка в терминах материала

2021-04-10 21:43 UTC, toplenboren commented on src/index.js
> +    {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
We do not need this

2021-04-10 21:43 UTC, toplenboren commented on src/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3"><g fill="#61DAFB"><path d="M666.3 296.5c0-32.5-40.7-63.3-103.1-82.4 14.4-63.6 8-114.2-20.2-130.4-6.5-3.8-14.1-5.6-22.4-5.6v22.3c4.6 0
Иконки обычно прячут в компоненты, чтобы не возиться со статикой

Например, было бы так:

```
function Logo() {
  return (
    <svg>...</svg>
  )
}
```

С таким подходом ты сможешь, например, динамически менять цвет у логотипа, или еще не бог весть что делать) Возможно для мобильной версии придется другой размер задавать

Но можно и так :)

2021-04-10 21:43 UTC, toplenboren commented on src/theme.js
> +import { red } from '@material-ui/core/colors';
theme я бы убрал поближе к инициализации Material, но это personal preference

2021-04-10 21:43 UTC, toplenboren commented on src/Components/App/App.js
> +class DB {
Ок на сейчас, но, возможно, у нас прямо поменяется структура данных

Круто, что ты это сделала!

2021-04-17 11:54 UTC, toplenboren approved these changes
Давай только подприберем код, и гоу идти дальше. Есличо - допишем-перепишем :)

2021-04-17 11:54 UTC, toplenboren commented on src/Components/App/App.css
> +.chats {
^^

2021-04-17 11:54 UTC, toplenboren commented on src/Components/App/App.js
> +    this.db.addMessage(this.state.name, document.getElementById('writeMessaage').value, true, time.getHours() + "." + time.getMinutes())
Чтобы сильно не страдать с датой, можно взять какое-нибудь решение по типу `date-fns`
 
 Если хотим страдать — лучше вынести функции по созданю нужной даты в utils, сделать на них юнит-тесты, и просить использовать во всем проекте
 
 Нам дофига где просто дата нужна будет

2021-04-17 11:54 UTC, toplenboren commented on src/Components/App/App.js
> +            <Grid item xs={4}>
👍

2021-04-17 11:54 UTC, toplenboren commented on src/Components/Header/Header.js
> +import './Header.css';
Давай уберем ./Header.css ? раз он нам уже не нужен?

2021-04-17 11:54 UTC, toplenboren commented on src/Components/Header/Header.js
> +import logo from './../../static/logo.png';
Статика в нашем приложении вставляется с `surge`, а не с локального хранилища.

В нашем случае — предлагаю ход конем сделать, и не использовать статику вообще. Давай попробуем вынести logo в компонент, который экспортирует `<svg>` ?

Ну типа, как будет:

```

export default function Logo() {
  return <svg>...</svg>
}

```

Логотип в `<svg>` нарисовал, вот:

```
<svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9.26162 51.6919L15.8486 18.7572C15.9508 18.246 16.3996 17.8781 16.9209 17.8781H45.5956C46.1039 17.8781 46.5451 18.2282 46.6606 18.7232L54.3454 51.6579C54.5054 52.3438 53.9847 53 53.2804 53H10.334C9.64388 53 9.12627 52.3686 9.26162 51.6919Z" stroke="black" stroke-width="3.28085"/>
<path d="M19.9581 45.7415C19.827 45.7415 19.7239 45.704 19.649 45.6291C19.5741 45.5542 19.5366 45.4511 19.5366 45.32V26.4946C19.5366 26.3635 19.5741 26.2605 19.649 26.1856C19.7239 26.1106 19.827 26.0732 19.9581 26.0732H24.3975C24.5286 26.0732 24.6316 26.1106 24.7066 26.1856C24.7815 26.2605 24.819 26.3635 24.819 26.4946V41.0492C24.819 41.1616 24.8752 41.2178 24.9875 41.2178H30.4666C30.5977 41.2178 30.7007 41.2552 30.7756 41.3302C30.8506 41.4051 30.888 41.5081 30.888 41.6392V45.32C30.888 45.4511 30.8506 45.5542 30.7756 45.6291C30.7007 45.704 30.5977 45.7415 30.4666 45.7415H19.9581Z" fill="black"/>
<path d="M43.9334 40.2063C43.9334 41.9858 43.3621 43.3532 42.2195 44.3085C41.0768 45.2638 39.6251 45.7415 37.8644 45.7415H31.9358C31.8046 45.7415 31.7016 45.704 31.6267 45.6291C31.5518 45.5542 31.5143 45.4511 31.5143 45.32V26.4946C31.5143 26.3635 31.5518 26.2605 31.6267 26.1856C31.7016 26.1106 31.8046 26.0732 31.9358 26.0732H37.0214C39.0632 26.0732 40.6554 26.5321 41.798 27.45C42.9594 28.3678 43.5401 29.754 43.5401 31.6084C43.5401 33.3317 43.0062 34.6148 41.9385 35.4578C41.8448 35.5327 41.8261 35.5983 41.8823 35.6544C43.2497 36.7034 43.9334 38.2207 43.9334 40.2063ZM36.9652 30.5969C36.8528 30.5969 36.7966 30.6531 36.7966 30.7655V33.5752C36.7966 33.6876 36.8528 33.7438 36.9652 33.7438H37.1057C37.9486 33.7438 38.3701 33.2193 38.3701 32.1704C38.3701 31.1214 37.9486 30.5969 37.1057 30.5969H36.9652ZM37.4429 41.2178C37.7988 41.2178 38.0891 41.0679 38.3139 40.7682C38.5387 40.4498 38.6511 40.0002 38.6511 39.4195C38.6511 38.8388 38.5387 38.3799 38.3139 38.0427C38.1079 37.6868 37.8269 37.5089 37.471 37.5089H36.9652C36.8528 37.5089 36.7966 37.5651 36.7966 37.6775V41.0492C36.7966 41.1616 36.8528 41.2178 36.9652 41.2178H37.4429Z" fill="black"/>
<circle cx="31.2439" cy="12.0244" r="5.38396" stroke="black" stroke-width="3.28085"/>
</svg>

```

2021-04-17 11:54 UTC, toplenboren commented on src/Components/Message/Message.css
> +.message, .myMessage {
Если нам все-таки не обойтись без `css` ,то давай лучше имновать по БЭМу, чтобы коллизий не было?

Типа, `message`, `message_mine`

2021-04-17 11:54 UTC, toplenboren commented on src/Components/Message/Message.css
> +.message, .myMessage {
https://ru.bem.info/methodology/css/

2021-04-17 11:54 UTC, toplenboren commented on src/Components/SendingMessage/SendingMessage.js
> +    if (document.getElementById('writeMessaage'))
О, а вот так в реакте делать не надо) 

Манипуляции с Dom нужно делать через состояния объектов (`setState`), а не напрямую.

Конкретно здесь это сработает, но вообще это антипаттерн. Чуть чуть подробнее можно прочитать [тут](https://reactjs.org/docs/integrating-with-other-libraries.html#:~:text=Integrating%20with%20DOM%20Manipulation%20Plugins,has%20no%20way%20to%20recover.):

2021-04-17 11:54 UTC, toplenboren commented on src/index.css
> +
Давай уберем неиспользуемый код?

2021-04-17 12:19 UTC, ya-woodcutter reviewed
За выбор react + material лойс

2021-04-17 12:19 UTC, ya-woodcutter commented on package.json
> +    "production": [
Думаю можно и в продовой сборке брать последние две версии браузера, чтобы бандл был более легким и использовал по максимуму фичи браузеров. Но тут Вам решать. Обычно широкую более широкую поддержку браузеров добавляют по необходимости... в нашем случае её вроде как нет.

2021-04-17 12:19 UTC, ya-woodcutter commented on public/index.html
> +    <title>React App</title>
Можно сразу пройтись по всем `React App` и заменить на актуальный `Килограмм` :)

2021-04-17 12:19 UTC, ya-woodcutter commented on src/Components/App/App.js
> +    this.db.addMessage(this.state.name, document.getElementById('writeMessaage').value, true, time.getHours() + "." + time.getMinutes())
Было бы по красоте написать хелперов для `Date`. Нужно оценить нужна ли Вам будет целая либа для работы с датами/временем. Если Вы от туда будете юзать пару хелперов, то лучше заюзать нативный код, т.к. либа [не бесплатная](https://bundlephobia.com/result?p=date-fns@2.20.3)

2021-04-21 16:40 UTC, toplenboren approved these changes
Супер!

Давай небольшие штуки поправим и гоу мерджить

2021-04-21 16:40 UTC, toplenboren commented on public/manifest.json
> +  "name": "Мессенжер Килограмм",
Мессенжер -> Мессенджер

2021-04-21 16:40 UTC, toplenboren commented on src/Components/App/App.js
> +import getFormattedDate from './../../utils/date.utils'
👍

2021-04-21 16:40 UTC, toplenboren commented on src/Components/Message/Message.css
> +.message, .my-message {
Давай эти классы тоже приведем к БЭМу?

Например, у нас будет `message` и `message_mine` потому что `_mine` это модификатор


`my-message -> message_mine`

`time-message -> message__time`

etc

2021-04-21 16:40 UTC, toplenboren commented on src/utils/date.utils.js
> +export default function getFormattedDate(date) {
Збс)

Еще тестами бы покрыть, но наверное в другой задаче

2021-04-21 17:16 UTC, merged