simple dockerized
urfu-2020/team-8 pull request #6
Opened 2021-04-11 09:27 UTC by Lenikas

2021-04-11 11:40 UTC, toplenboren requested changes

2021-04-11 11:40 UTC, toplenboren commented on .env
> +PORT = 2121
Нам точно нужен `.env` в гите? 

А если захотим тут сторить какие-то креды, или соль для паролей, или что-то такое?

Возможно, лучше сделать `.env.example` файл, с примерами переменных окружения и заствлять разработчика делать  

`cp .env.example .env`

`nano .env`

А чтобы не страдать, давай в докерфайле зафигачим сразу же стандартный порт. Но дадим возможность переопределить.

2021-04-11 11:40 UTC, toplenboren commented on Dockerfile
> +CMD ["node", "app/index.js"]
Сюда по хорошему запускать бы npm run-script start, так мы ответственность за запуск приложения положим на `package.json` и все будет в одном месте.

Что думаешь?

2021-04-11 11:40 UTC, toplenboren commented on Dockerfile
> +#COPY package-lock.json /
`package.lock.json` полезная штука на самом деле, гоу либо уберем коммент, либо уберем строку?

2021-04-11 11:40 UTC, toplenboren commented on Dockerfile
> +# RUN npm ci --production
Давай тут тоже уберем комментарии?

2021-04-11 12:26 UTC, Lenikas commented on app/index.js
> +    res.writeHead(301, {Location: surgeDomain})
может быть это делается не так топорно,но для пробника сойдет

2021-04-11 12:46 UTC, Lenikas commented
реквест помойка,уж простите

2021-04-11 15:06 UTC, toplenboren approved these changes
Поправь только последнее замечание плиски

2021-04-11 15:06 UTC, toplenboren commented on Dockerfile
> +RUN npm ci --production
Если мы оставляем `npm ci` то нам не нужен `npm install` и нужен всегда актуальный `package.lock.json`

Для этого нужно всей команде использовать `npm` а не `yarn`

--


Иначе можно оставить просто `npm install` а `npm ci` убрать

https://habr.com/ru/post/350762/

2021-04-12 05:44 UTC, Lenikas commented on Dockerfile
> +RUN npm ci --production
понял,не шарю просто за эту штуку совсем
давайте оставим npm, он хоть как-то знакомо выглядит
спасибо,что пояснил

2021-04-12 05:52 UTC, merged